### ISSUE TITLE
poppler-qt5: wrong Qt5Core version

### ISSUE THREAD

**Issue by 21stcaveman** [RJVB/macstrop#100]
number 100.. here we go:
trying to upgrade poppler-qt5, seems like it is looking for QT5 5.12 and fails:

CMake Error at CMakeLists.txt:162 (MESSAGE):
  Could not find the 5.12 version of Qt5Core.  If you're not interested in
  the features it provides set the cmake ENABLE_QT5 option to OFF
Call Stack (most recent call first):
  CMakeLists.txt:212 (find_soft_mandatory_package)

I assume it is because I'm using qt5-kde which provides 5.9.8

**Comment by 21stcaveman** [comment]
I do, been using Kate, Dolphin and Konsole for some years now on my mac thanks to you. Specially Dolphin.

**Comment by RJVB** [comment]
Damn. I don't see how that can be, but at the moment I'm in big shit myself. My X11 environment refuses to start, and it's there that I did all my work >:(

**Comment by 21stcaveman** [comment]
oh no.. this can wait, wish you luck fixing that!

**Comment by RJVB** [comment]
Thanks!

**Comment by 21stcaveman** [comment]
was upgrading the system again, and ran into issues with poppler again. Looked at the patch you merged on Jan 31st, and that doesn't seem to be working as intended as I had to resolve two issues in order to build poppler: change QT version from 5.12 to 5.9 in CMakeLists.txt, AND change C++ standard from 20 to 17 in the same file.
Judging by the fact that I still had C++ standard set to 20 after the patch stage, it seems like that commit is not doing what it was supposed to. Just fyi

**Comment by RJVB** [comment]
On Monday May 06 2024 10:03:21 Hamid wrote:
>doesn't seem to be working as intended as I had to resolve two issues in order to build poppler: change QT version from 5.12 to 5.9 in CMakeLists.txt, 

Does the patchfile `patch-allow-older-deps.diff` not get applied on your end? It does for me... and it sets the minimum Qt5 version to 5.8 .

>AND change C++ standard from 20 to 17 in the same file.
>Judging by the fact that I still had C++ standard set to 20 after the patch stage, it seems like that commit is not doing what it was supposed to. Just fyi

That's even weirder, because poppler 24.01.0 has CXX_STANDARD 17 in its CMake file. Are you certain you're installing my port? ;)

**Comment by 21stcaveman** [comment]
nevermind... I'm dumb! somehow, I have switched to 24.04.0 ..

**Comment by RJVB** [comment]
>nevermind... I'm dumb! somehow, I have switched to 24.04.0 ..

Welcome to the club ;)

Does the patchfile still apply (and the premise old that Qt5.8 is supported)?

**Comment by 21stcaveman** [comment]
yup, 24.04.0 builds with those modifications.

**Comment by RJVB** [comment]
Thanks. I might decide to update my port then...
