### ISSUE TITLE
icu uses external python which may not exist: `/usr/bin/python: No such file or directory`

### ISSUE THREAD

**Issue by barracuda156** [RJVB/macstrop#116]
```
Not rebuilding data/rules.mk, assuming prebuilt data in data/in
Spawning Python to generate test/testdata/rules.mk...
./configure: line 9310: /usr/bin/python: No such file or directory
configure: error: Python failed to run; see above error.
./runConfigureICU: ./configure failed
Command failed:  cd "/opt/local/var/macports/build/_home_svacchanda_macstrop_devel_icu/icu/work/icu/source" && ./runConfigureICU Linux --prefix=/opt/local --disable-layoutex --disable-samples --enable-static 
Exit code: 1
Error: Failed to configure icu: consult /opt/local/var/macports/build/_home_svacchanda_macstrop_devel_icu/icu/work/icu/source/config.log
Error: Failed to configure icu: configure failure: command execution failed
Error: See /opt/local/var/macports/logs/_home_svacchanda_macstrop_devel_icu/icu/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port cmake failed
```

**Comment by RJVB** [comment]
Could you be a little more helpful, like offering a solution or telling where your system python lives if not under /usr/bin/python ?!

**Comment by barracuda156** [comment]
@RJVB Will it be problematic to use MacPorts one? That works. Otherwise we can just close the issue, if `/usr/bin/python` was intended for non-macOS. (If the issue is just with my system, there is no need for a general fix, I can keep a local one.)

**Comment by RJVB** [comment]
>@RJVB Will it be problematic to use MacPorts one? That works. Otherwise we can just close the issue, if `/usr/bin/python` was intended for non-macOS. (If the issue is just with my system, there is no need for a general fix, I can keep a local one.)

The mainstream icu Portfile has some comments about why it uses the system python preferentially: to avoid circular dependencies. As you know, MacPorts doesn't have ports for installing the python or python3 wrappers, like it has for perl, so dependents either have to include all kinds of logic to support an automatic (or user) choice from the available python-x.y executables, or hardcode a specific version. The latter is extremely annoying, the former cumbersome (it's code that should be provided by the python PortGroup).

The possible trick with port:icu would be to let it check for suitable MacPorts python interpreters over one installed by the host.

Didn't you already install patchelf, or is that why you're trying to install port:icu? Patchelf is required by port:python39 so I'm guessing you didn't install that one yet...

**Comment by barracuda156** [comment]
Patchelf is installed, I got everything up to CMake built.
I did change dependencies from system prefix to MacPorts is 3–4 cases, since Python was missing in the former and Perl was breaking the build of autoconf and libtool.
