### ISSUE TITLE
libgcc depends on itself, which breaks gcc13

### ISSUE THREAD

**Issue by barracuda156** [RJVB/macstrop#123]
This is what, apparently, made impossible to try installing gcc13:
```
--->  Computing dependencies for gcc13.Error: Unable to execute port gcc13: child process exited abnormally
sh-5.1# port installed libgcc
None of the specified ports are installed.
sh-5.1# port -v install libgcc
Warning: configured user/group macports does not exist, will build as root
--->  Computing dependencies for libgcc..
The following dependencies will be installed:  libgcc
Continue? [Y/n]: y
Error: The following dependencies were not installed because all of them have unmet dependencies (likely due to a dependency cycle): libgcc
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port libgcc failed
sh-5.1# port file libgcc
/home/svacchanda/macstrop/lang/libgcc/Portfile
sh-5.1# port deps libgcc
Full Name: libgcc @7.0_1+gcc13
Build Dependencies:   
Library Dependencies: libgcc13, libgcc
```

**Comment by RJVB** [comment]
On Thursday September 19 2024 16:27:35 Sergey Fedorov wrote:

>sh-5.1# port deps libgcc
>Full Name: libgcc @7.0_1+gcc13
>Build Dependencies:   
>Library Dependencies: libgcc13, libgcc


That doesn't make sense. The libgcc Portfile has a single `depends_lib` statement which doesn't do an -append so there is no way that it could ever generate a double dependency itself.

I cannot reproduce this, neither with 2.7.1 nor 2.10.x nor after adding an up-to-date compilers-1.0 PG to MacStrop. Do you have any local modifications that add a port:libgcc dependency?

**Comment by barracuda156** [comment]
> On Thursday September 19 2024 16:27:35 Sergey Fedorov wrote: sh-5.1# port deps libgcc Full Name: libgcc @7.0_1+gcc13 Build Dependencies: Library Dependencies: libgcc13, libgcc
> That doesn't make sense. The libgcc Portfile has a single `depends_lib` statement which doesn't do an -append so there is no way that it could ever generate a double dependency itself. I cannot reproduce this, neither with 2.7.1 nor 2.10.x nor after adding an up-to-date compilers-1.0 PG to MacStrop. Do you have any local modifications that add a port:libgcc dependency?

Should not be, but let me think. Ports and PGs in lnxports and macstrop are untouched, with the exception of sorting libiconv and isl issues here: https://github.com/barracuda156/lnxports (I cannot see how this could possibly affect libgcc dependencies, and also this is a new commit, while I had this dependency error from the get-go).

I have probably set the base to prefer gcc for riscv64; that probably should not have introduced a dependency cycle. After all, I do not get it on powerpc, where gcc is preferred.

**Comment by RJVB** [comment]
Does `port -vd info libgcc` teach you anything?

IF the problem goes away when you use `configure.compiler=clang` or set the default compiler to clang in macports.conf, is there anything different in the output from the above command (apart the dependency of course)?

If all else fails you can always ask on the ML if there's any port developer's trick that can help you pinpoint where a component gets added to depends_lib. If I do that it'll just get ignored.

**Comment by RJVB** [comment]
Doh, I don't know how I overlooked the culprit this morning!

**Comment by barracuda156** [comment]
Hmm, something does not work for me still:
```
sh-5.1# port deps libgcc
Full Name: libgcc @7.0_1+gcc13
Build Dependencies:   
Library Dependencies: libgcc13
sh-5.1# port -v install libgcc
Warning: configured user/group macports does not exist, will build as root
--->  Computing dependencies for libgcc.
--->  Configuring libgcc
Error: Failed to configure libgcc: invalid bareword "neN"
in expression "${os.platform} neN "darwin" || ${os.majo...";
should be "$neN" or "{neN}" or "neN(...)" or ...
Error: See /opt/local/var/macports/logs/_home_svacchanda_macstrop_lang_libgcc/libgcc/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port libgcc failed
```
