### ISSUE TITLE
VLC-test: VLC.app not created

### ISSUE THREAD

**Issue by michaellass** [RJVB/macstrop#16]
I just tested VLC-test on a current macOS Mojave (because of https://trac.macports.org/ticket/57260). It seems to compile fine but does not create an .app bundle, so it fails in destroot when trying to copy VLC.app.

Not sure if this is a Mojave / XCode 10 issue or if some step is missing to create VLC.app. All contents seem to be present under `bin` (i.e., binaries and a Contents folder with Info.plist).

Variants were +quartz -x11. Full build log is attached.

[VLC-test.log](https://github.com/RJVB/macstrop/files/2450635/VLC-test.log)

**Comment by michaellass** [comment]
OK, it looks like we need to set `destroot.target VLC.app` to build the application bundle. However, this also fails:
```
rm -Rf VLC.app
cp -R /opt/local/share/macosx/ VLC.app
cp: /opt/local/share/macosx/: No such file or directory
make: *** [VLC.app] Error 1
make: Leaving directory `/opt/local/var/macports/build/_Users_lass_ports_multimedia_VLC-test/VLC-test/work/vlc-3.0.4'
Command failed:  cd "/opt/local/var/macports/build/_Users_lass_ports_multimedia_VLC-test/VLC-test/work/vlc-3.0.4" && /usr/bin/make -w VLC.app DESTDIR=/opt/local/var/macports/build/_Users_lass_ports_multimedia_VLC-test/VLC-test/work/destroot 
Exit code: 2
Error: Failed to destroot VLC-test: command execution failed
```

**Comment by RJVB** [comment]
Looks like I have some comparing of configure.ac and/or Makefile.am in my future. But don't let that stop anyone else from looking; I wouldn't mind if someone else finds the issue before me ;)

**Comment by michaellass** [comment]
I managed to get VLC.app built and installed. See PR #17. In a quick test, VLC seemd to behave fine under Mojave.
