### ISSUE TITLE
Add krita

### ISSUE THREAD

**Issue by eirnym** [RJVB/macstrop#2]
Please, add Krita standalone build

I know Calligra contains Krita, but I want just use only Krita, without all Calligra suite.

**Comment by RJVB** [comment]
On Monday May 09 2016 09:37:57 Arseny Nasokin wrote:
>Please, add Krita standalone build
>
>I know Calligra contains Krita, but I want just use only Krita, without all Calligra suite.

The closest I intend to support is the standard build, which installs only the applications that are of use for creative purposes: krita, karbon, the presentation module (Stage), Braindump and Kexi. I've never checked how much more space this takes up, but then I am not particularly interested myself in installing only Krita.

We'll see when the KF5 Calligra suite nears release. If by then my KF5 port tree has been included in MacPorts I may consider making each component available through its own variant.

**Comment by RJVB** [comment]
There's now a port:kf5-krita that you can try.
