### ISSUE TITLE
kf5-kio fails to build with /opt/local/include/sys/acl.h error

### ISSUE THREAD

**Issue by gitdevmod** [RJVB/macstrop#27]
See log file
[main.log](https://github.com/RJVB/macstrop/files/2760716/main.log)
Similar issue with qt5-webkit

**Comment by gitdevmod** [comment]
It's build correctly after replace

**Comment by RJVB** [comment]
>It's build correctly after replace

You mean that `EXPORT` been replaced with `extern` everywhere? The reinplace log message you copied is a bit suspect, shows there's an issue with special character escaping. I should have realised that :-/

But the fact that nothing is being reinplaced also shows that the other part of the tentative fix, using gmake, is enough in and by itself, apparently.

**Comment by RJVB** [comment]
OK, I pushed a revbump for what I take as a confirmed fix :)

**Comment by gitdevmod** [comment]
After updating sysutils/acl EXPORT is not replaced by extern

`$ sudo port upgrade outdated
Portfile changed since last build; discarding previous state.
--->  Computing dependencies for acl
--->  Fetching distfiles for acl
--->  Verifying checksums for acl
--->  Extracting acl
--->  Applying patches to acl
--->  Configuring acl
--->  Building acl
--->  Staging acl into destroot
Warning: reinplace s|\<EXPORT\>|extern|g didn't change anything in /opt/local/var/macports/build/_opt_local_macstrop_sysutils_acl/acl/work/destroot/opt/local/include/sys/acl.h
Warning: reinplace s|\<EXPORT\>|extern|g didn't change anything in /opt/local/var/macports/build/_opt_local_macstrop_sysutils_acl/acl/work/destroot/opt/local/include/acl/libacl.h
--->  Installing acl @2.5.53_1
--->  Cleaning acl
--->  Computing dependencies for acl
--->  Deactivating acl @2.5.53_0
--->  Cleaning acl
--->  Activating acl @2.5.53_1
--->  Cleaning acl
`

**Comment by RJVB** [comment]
The regexp syntax used here (for sed, the underlying command that does the work) means "replace the whole word EXPORT".

The argument seems to work for me when used via my commandline version of the reinplace command (and a copy of acl.h in which all extern keywords have been replaced by EXPORT)

```
> reinplace.tcl -v 's|\<EXPORT\>|extern|g' acl.h
```

R.

**Comment by gitdevmod** [comment]
@RJVB How to use reinplace.tcl ? 
It fails with

$ /opt/local/macstrop/macports/bin/reinplace.tcl -v 's|\<EXPORT\>|extern|g' /opt/local/include/acl/libacl.h 
can't read "os_subplatform": no such variable
    while executing
"subst {$os_subplatform}"
    invoked from within
"set os.subplatform [subst {$os_subplatform}]"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list set $optionName] [subst -nocommands {[subst {$option_defaults($optionName)}]}]"
    (procedure "default_check" line 10)
    invoked from within
"default_check os.subplatform {} r"
    (read trace on "os.subplatform")
    invoked from within
"set $option"
    (procedure "option" line 10)
    invoked from within
"option os.subplatform"
    invoked from within
"if {[option os.platform] eq "darwin" && [option os.subplatform] eq "macosx"} {
    # we're on Mac OS X and can therefore build universal
    default o..."
    (file "/opt/local/libexec/macports/lib/port1.0/portmain.tcl" line 140)
    invoked from within
"source /opt/local/libexec/macports/lib/port1.0/portmain.tcl"
    ("package ifneeded portmain 1.0" script)
    invoked from within
"package require portmain 1.0"
    (file "/opt/local/libexec/macports/lib/port1.0/port.tcl" line 66)
    invoked from within
"source /opt/local/libexec/macports/lib/port1.0/port.tcl"
    ("package ifneeded port 1.0" script)
    invoked from within
"package require port 1.0"
    (file "/opt/local/macstrop/macports/bin/reinplace.tcl" line 32)

**Comment by Tatsh** [comment]
Is this still relevant? I have kf5-kio installed now and never had an issue like this.

**Comment by RJVB** [comment]
Hmm, thanks. I usually leave it up to the reporter to close issues I couldn't reproduce myself, when they confirm that they're fixed. Guess that's now confirmed. :)
