### ISSUE TITLE
Documentation on KF5, workarounds, etc?

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#31]
Wondering if you'd be open to a separate markdown file for notes on KF5 apps and workarounds for various issues as they are discovered. I can submit a PR.

One item I would note is that while a lot of settings will not show up in `systemsettings` they can still be set in `~/.config/kdeglobals`. For example to enable double-clicking for files in Dolphin and other managers:

```ini
[KDE]
SingleClick=false
```

**Comment by RJVB** [comment]
> Wondering if you'd be open to a separate markdown file for notes on KF5 apps and workarounds for various issues as they are discovered.

Of course, why not? A number of those things are already mentioned on the MacPorts Wiki, KDE entry.

> One item I would note is that while a lot of settings will not show up in `systemsettings` they can still be set in `~/.config/kdeglobals`. For example to enable double-clicking for files in Dolphin and other managers:

Hah, I'd have sworn that used to be accessible through one of the KCMs I managed to install...

The real solution here would be to write a KCM (or collection of) for cross-platform use that are either acceptable for the Plasma guys or are simply a separate project outside of their control. The consensus is that there should be a "native" configuration method but I don't see that happening (outside of a Preference Panel that triggers the launch of the KDE systemsettings application, on Mac).

**Comment by Tatsh** [comment]
If I have something for this I will make a PR.
