### ISSUE TITLE
cmake 1.1: strange error message when running  `sudo port uninstall inactive`

### ISSUE THREAD

**Issue by mkae** [RJVB/macstrop#4]
This I saw on a 10.9.5 with `qt5-kde-devel`:
```
--->  Cleaning kf5-kdevplatform-devel
Error: Unable to open port: can't set "cmake.generator": The "{"Unix Makefiles"}" cmake generator is not currently known/supported
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
```
What is that now?

**Comment by RJVB** [comment]
On Friday November 11 2016 15:56:32 Marko K�ning wrote:

> --->  Cleaning kf5-kdevplatform-devel
> Error: Unable to open port: can't set "cmake.generator": The "{"Unix Makefiles"}" cmake generator is not currently known/supported
> To report a bug, follow the instructions in the guide:
>     http://guide.macports.org/#project.tickets
> ```
> What is that now?

Did the port uninstall? I cannot reproduce it here. Sometimes you get transient errors during uninstall and deactivate, I hope this is (was) such a thing.

Night!
R.

**Comment by mkae** [comment]
Well, yes, see the issue's title! ;-) It was an uninstall, of course. OK, we'll see whether it is going to happen again.

**Comment by mkae** [comment]
So, running into this again:
```
$ port installed outdated
The following ports are currently installed:
  kf5-kdev-python-devel @5.0.2.79_0+qt5kde (active)
  kf5-kdevelop-clang-parser-devel @5.0.2.635_0+llvm38+qt5kde (active)
  kf5-kdevelop-devel @5.0.2.635_0+qt5kde (active)
  kf5-osx-integration-devel @5.26.0.2_0+qt5kde (active)
  nspr @4.13_0 (active)
  p5.24-podlators @4.80.0_0 (active)
  py27-cryptography @1.5.2_0 (active)
$ sudo port upgrade outdated
Error: Unable to open port: can't set "cmake.generator": The "{"Unix Makefiles"}" cmake generator is not currently known/supported
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
```
although I have pulled the latest version from macstrop and eventually even copied the cmake-1.1.tcl in place (which I hadn't earlier), but still I get this!!!

**Comment by RJVB** [comment]
On Saturday November 12 2016 03:04:43 Marko K�ning wrote:

> $ sudo port upgrade outdated
> Error: Unable to open port: can't set "cmake.generator": The "{"Unix Makefiles"}" cmake generator is not currently known/supported

Can you send me the relevant log, please?
Actually, please copy/paste the relevant bit from it in a message, then pull the new cmake-1.1 version I just uploaded and tell me if the issue persists.

Sorry for this...

R.

**Comment by mkae** [comment]
With your latest update to the portgroup file it does work fine. :)
