### ISSUE TITLE
libaacs should pull in Bison

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#41]
libaacs has a syntax error when used with the macOS' `/usr/bin/yacc`. Installing `bison @3.3.2` fixes this issue.

**Comment by RJVB** [comment]
On Monday March 18 2019 20:37:16 Tatsh wrote:
>libaacs has a syntax error when used with the macOS' `/usr/bin/yacc`. Installing `bison @3.3.2` fixes this issue.
>
>

The port already has a build dependency on bison:

```
depends_build       port:perl5 \
                    bin:flex:flex \
                    bin:bison:bison \
                    port:gettext
```

Do you by any chance also have /usr/bin/bison?

**Comment by Tatsh** [comment]
Yes it comes with macOS (or maybe it gets placed here by Xcode). It's protected by SIP.

```
 $ /bin/ls -laO /usr/bin/bison
-rwxr-xr-x  1 root  wheel  restricted,compressed 18288 Feb  5 00:28 /usr/bin/bison
```

**Comment by RJVB** [comment]
SIP doesn't really matter here, the question is more what version you have.

Can you confirm that this is actually the command that was used and failed?

For the record: I use a `bin:bison` type of depspec exactly because it allows to use any available bison. I did that to avoid having to install port:bison on my Linux rig; the system bison is v3.0.2 there.

**Comment by Tatsh** [comment]
The command is `bison -y` without a path, which resolves to Apple's `/usr/bin/bison` by default. On Mac, maybe it should be `port:bison` depspec?

**Comment by Tatsh** [comment]
Unless you want to patch it:

```
... libaacs/work/libaacs-0.9.0/src/file/keydbcfg-parser.y:1.1-5: invalid directive: `%code'
... libaacs/work/libaacs-0.9.0/src/file/keydbcfg-parser.y:1.7-14: syntax error, unexpected identifier
```

**Comment by RJVB** [comment]
I've already pushed a change to the depspec; doesn't that fix the issue?

**Comment by Tatsh** [comment]
Yes it is fixed.
