### ISSUE TITLE
VLC @3.0.6 +langselect+quartz+smb+svg-dbus-x11 fails to build

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#42]
[main.log](https://gist.githubusercontent.com/Tatsh/ac27f056068c24446c2b21a9b7a24b15/raw/775704276f3b49b7f67d944903a3fb60d5347b0f/vlc-main.log)

**Comment by RJVB** [comment]
Hopefully this is just because I didn't yet integrate the fix from the main tree that solves a libssh2 issue. Did so now; can you please pull and try again?

**Comment by Tatsh** [comment]
Works now.

Could you make the SFTP support optional via a variant? (and disable by default)

Gentoo does this with `--disable-sftp`: https://github.com/gentoo/gentoo/blob/master/media-video/vlc/vlc-3.0.6-r1.ebuild

**Comment by RJVB** [comment]
I could, but what would be the advantage? The idea of the VLC port is that it corresponds as much as possible to the official build when using the default options.
