### ISSUE TITLE
Qt environment variables and workaround

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#44]
I am setting `QT_QPA_PLATFORMTHEME` globally with `~/.MacOSX/environment.plist`.

I found that some Qt apps like Wireshark (which I am not installing with MacPorts due to conflicts with the original Qt 5 packages) will read the environment variables `QT_QPA_PLATFORMTHEME` and will either look incorrect or will crash. In general they are buggy.

The workaround for any app bundle is to set the `LSEnvironment` key in `Info.plist`:

```xml
        <key>LSEnvironment</key>
        <dict>
                <key>QT_QPA_PLATFORMTHEME</key>
                <string></string>
        </dict>
```

You have to force macOS to reread `Info.plist`. One way is to use `touch(1)`.

**Comment by RJVB** [comment]
Thanks, I'm aware of this, but what do you want me to do with it? It's not something you can set through the port unless you want to force a specific platform theme on everyone.

Where does the `QT_QPA_PLATFORMTHEME2` variable come from?

**Comment by Tatsh** [comment]
My mistake. I think I mistyped it at some point a long time ago and thought it was relevant.

I think the best solution is to provide a note about this in the Qt Portfile.

**Comment by Tatsh** [comment]
```diff
diff --git a/kf5/KF5-Frameworks/Portfile b/kf5/KF5-Frameworks/Portfile
index 9108ed2b..7a5f9c67 100644
--- a/kf5/KF5-Frameworks/Portfile
+++ b/kf5/KF5-Frameworks/Portfile
@@ -2080,7 +2080,7 @@ subport kf5-plasma-framework {
         if {[vercmp [qt5.active_version] 5.11.0] < 0 &&
             [vercmp ${kf5.latest_qt59_version} ${kf5.dep_version}] <0} {
             reinplace -q \
-                    "s|KF5_DEP_VERSION \"${kf5.dep_version}\"|KF5_DEP_VERSION \"${kf5.latest_qt59_version}\"|g"
+                    "s|KF5_DEP_VERSION \"${kf5.dep_version}\"|KF5_DEP_VERSION \"${kf5.latest_qt59_version}\"|g" "${worksrcpath}/CMakeLists.txt"
         }
         reinplace "s|/usr/share/inkscape|${prefix}/share/inkscape|g" "${worksrcpath}/src/tools/inkscape extensions/plasmarename.py"
         reinplace "s|/usr/bin/perl|${prefix}/bin/perl5|g" ${worksrcpath}/src/tools/currentColorFillFix.sh
diff --git a/kf5/kf5-osx-integration/Portfile b/kf5/kf5-osx-integration/Portfile
index 3353591d..f14f57d7 100644
--- a/kf5/kf5-osx-integration/Portfile
+++ b/kf5/kf5-osx-integration/Portfile
@@ -67,6 +67,8 @@ if {${subport} eq "${name}-devel"} {
     epoch           2
     worksrcdir      ${name}-5
     distname        ${name}-5
+    patchfiles cxx.patch
+    patch.pre_args      -p1
 } else {
     github.setup    RJVB osx-integration 0
     github.tarball_from releases
@@ -77,6 +79,7 @@ if {${subport} eq "${name}-devel"} {
     description     ${description} This port doesn't have a release version yet.
     long_description \
                     ${long_description} This port doesn't have a release version yet.
+
     pre-fetch {
         ui_error "This port doesn't have a release version (yet), use ${name}-devel instead."
         return -code error "This port doesn't have a release version (yet)."
```

cxx.patch is just one of the patches above.

**Comment by Tatsh** [comment]
For KDE apps I think the best solution is to add these values to the generated Info.plist prior to installation:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>LSEnvironment</key>
        <dict>
                <key>QT_QPA_PLATFORMTHEME</key>
                <string>kde</string>
                <key>KDE_SESSION_VERSION</key>
                <string>5</string>
        </dict>
</dict>
</plist>
```

This could be done with `/usr/libexec/PlistBuddy`. Have a file with the above contents (`env-vars.plist`) and then run:

```
/usr/libexec/PlistBuddy -xc 'Merge env-vars.plist' somewhere/kate.app/Contents/Info.plist
```

I've been manually patching these after install.

**Comment by RJVB** [comment]
I'd have to put that into a variant, and I'd have to figure out a way to do this that doesn't oblige me to know exactly where each port puts its plists. That's not something very high on my lists, to be honest.

The current instructions should be clear enough that users set the variables in their environment via a 1-time edit of a single or handful of files, and to the exact values they want to set them to.

**Comment by Tatsh** [comment]
On macOS, [this tool](https://github.com/hschmidt/EnvPane) works. On Catalina with the release, it must be explicitly allowed in the *Security* section in *System Preferences*.
