### ISSUE TITLE
libbluray @1.1.1 fails to build

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#46]
This is after I install *apache-ant* (maybe this should be pulled in?). libbluray is pulled in by ffmpeg, VLC and mpv.

```
compile:
    [javac] /opt/local/var/macports/build/_Users_tatsh_dev_macstrop_multimedia_libbluray/libbluray/work/libbluray-1.0.1/src/libbluray/bdj/build.xml:24: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 22 source files to /opt/local/var/macports/build/_Users_tatsh_dev_macstrop_multimedia_$ibbluray/libbluray/work/libbluray-1.0.1/src/libbluray/bdj/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 5
    [javac] error: Source option 5 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.
```

**Comment by RJVB** [comment]
On Saturday June 01 2019 06:19:02 Tatsh wrote:
> This is after I install *apache-ant* (maybe this should be pulled in?). libbluray is pulled in by ffmpeg, VLC and mpv.

Pray tell, how were you trying to build v1.1.1? My port was still at 1.0.1 ... and the mainstream version doesn't enable the Java stuff.

I've just pushed an upgrade of my own version, please pull, clean and try again.

R.

**Comment by Tatsh** [comment]
Works. Thanks
