### ISSUE TITLE
This source's Cairo port conflicting with MacPorts' librsvg port?

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#48]
I am getting this error from librsvg:

```
:info:configure checking for    cairo >= 1.15.12                cairo-png >= 1.15.12            freetype2 >= 20.0.14            gdk-pixbuf-2.0 >= 2.20  gio-2.0 >= 2.24.0                       glib-2.0 >= 2.48.0              libxml-2.0 >= 2.9.0             pangocairo >= 1.38.0            pangoft2 >= 1.38.0                    libcroco-0.6 >= 0.6.1... no
:info:configure configure: error: Package requirements (        cairo >= 1.15.12                cairo-png >= 1.15.12            freetype2 >= 20.0.14            gdk-pixbuf-2.0 >= 2.20  gio-2.0 >= 2.24.0
        glib-2.0 >= 2.48.0              libxml-2.0 >= 2.9.0             pangocairo >= 1.38.0            pangoft2 >= 1.38.0                    libcroco-0.6 >= 0.6.1) were not met:
:info:configure Requested 'cairo >= 1.15.12' but version of cairo is 1.14.8
:info:configure Requested 'cairo-png >= 1.15.12' but version of cairo-png is 1.14.8
```

This source provides `cairo @1.14.8` and running `port upgrade -f cairo` refuses to update to MacPorts own `cairo @1.16.0`. This source does not provide its own librsvg, which is needed by a few packages from here like VLC and ffmpeg.

**Comment by RJVB** [comment]
Can you pull and confirm if the clamped librsvg version I just introduced worked?

If it doesn't you can always install cairo from the main tree; just run `port install` WITHOUT the port name (but with any of the variants you want) from inside the port directory (`graphics/cairo` under your main port tree directory).

**Comment by Tatsh** [comment]
This new librsvg fixes the issue. I am doing a rev-upgrade which will rebuild ffmpeg, gegl-devel, gimp2-devel, and VLC and will report back.
