### ISSUE TITLE
Port name and portdir mismatches

### ISSUE THREAD

**Issue by yan12125** [RJVB/macstrop#50]
Whenever running `portindex` in this repository, 18 ports are re-parsed:
```
$ portindex
Creating port index in /Users/yen/var/syncthing/Projects/macstrop
Adding port kde/ECM
Adding subport kde-extra-cmake-modules-devel
Adding subport kECM
Warning: depends_libs change: path:lib/libQtCore.4.dylib:qt4-mac
Warning: Using the mainstream/official Qt4 portgroup
Adding port kde/krecipe
Adding port kf5/kde-cli-tools
Adding port kf5/kdevelop5-pg-qt
Adding subport kf5-kdevelop-pg-qt-devel
Adding port kf5/kdevplatform5
Adding subport kf5-kdevplatform-devel
Adding subport kf5-kdevplatform-translations
Adding port kf5/kf5-libkcalcore
Adding port kf5/kompare5
Adding port kf5/konsole5
Adding subport kf5-konsole-devel
Adding port kf5/kwalletman
Adding port kf5/libkompare5diff2
Adding port kf5/okteta5
Adding port x11/oxygen-gtk3

Total number of ports parsed:	18
Ports successfully parsed:	18
Ports failed:			0
Up-to-date ports skipped:	1052
```
Looks like the cause is mismatches between port name and portdir. For example, the port in `kde/ECM` has the name `kde-extra-cmake-modules`.

**Comment by RJVB** [comment]
True. It has never really bothered me. What does bother me a bit more is having to rename workdirs when I rename a portdir, in the cases where that's necessary (and the port in question is one for which I do incremental development). So this is something that will get sorted out little by little.

**Comment by yan12125** [comment]
Sounds more like a missing feature in portindex. Feel free to close this ticket if you think this should be reported to macports-base :)

**Comment by RJVB** [comment]
Exactly what kind of missing feature?

**Comment by yan12125** [comment]
The ability to cache port info even if portdir != port name.
