### ISSUE TITLE
meson fails to build if py3*-setuptools is not installed

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#52]
The log showed it was looking for setuptools. Solution for me was to install py35-setuptools at least temporarily.

Also, this package is out of date. MacPorts now has version 0.51.1.

**Comment by RJVB** [comment]
Thanks, will look into it when I get a chance.

**Comment by Tatsh** [comment]
I think I may have had my system in a strange state at the time. I will close this for now.

I am not able to run a normal port upgrade outdated because I'm on Catalina and this means building everything from source. A number of packages in the main tree do not build (likely because they haven't been under any serious maintenance for a long time). Because I am dealing with this issue (where I upgrade packages individually), I may have had my system in a weird state trying to fix something else.

**Comment by RJVB** [comment]
The joys of upgrading the OS way earlier than strictly necessary. If I wanted that I'd be running Gentoo or Arch ;)

**Comment by Tatsh** [comment]
Ran into this issue again. Trying to upgrade glib-networking (currently broken from source). Your Meson port does not pull in py3*-setuptools.

[main.log](https://github.com/RJVB/macstrop/files/3491043/main.log)

**Comment by Tatsh** [comment]
I was running into a strange error when trying to install glib-networking (from core) and could not really find related issues on Meson's issues. The patch I made patches the call to `darwin_get_object_archs` so the `PosixPath` object is cast to a string. Newer versions of Meson have this area of code different as of 3 months ago so this may have been fixed but it's not back-portable.

**Comment by RJVB** [comment]
How so, my port doesn't pull in pyXY-setuptools?

```
> port info meson +python37
meson @0.51.1 (devel, python)
Variants:             python35, python36, +python37

Description:          Meson is a build system designed to optimize programmer productivity. It aims to SNIP
Homepage:             https://mesonbuild.com/

Build Dependencies:   py37-setuptools
Library Dependencies: python37
Runtime Dependencies: py37-setuptools, ninja
Platforms:            darwin
License:              Apache-2
Maintainers:          Email: git@soap.za.net, GitHub: SoapZA
                      Policy: openmaintainer
```

Meson appears to be up-to-date according to livecheck, so I don't really see what the probem is here.
As to glib-networking: does it no longer have the option to build with configure (autoconf/automake)?
