### ISSUE TITLE
pulseaudio fails to link: library not found for -lgcc_s.10.5

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#53]
Missing dep?

[main.log](https://github.com/RJVB/macstrop/files/3467577/main.log)

**Comment by RJVB** [comment]
>Missing dep?

No, without more details I'd say the build system mis-identifies the OS, or it's an issue with compiler blacklisting. I never used 10.5 so I cannot confirm nor infirm if there was a libgcc_s.10.5 there...

I see my port is considerably out-of-date (I can't even remember why I forked it in the first place...). Could you try to build the version in the official tree (12.2_2):

```
> cd /path/to/macports-ports/audio/pulseaudio ; port -nv  build
```
