### ISSUE TITLE
kf5-kconfig: linker error

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#55]
```
:info:build Undefined symbols for architecture x86_64:
:info:build   "KConfigTest::testQStringUtf8()", referenced from:
:info:build       KConfigTest::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) in mocs_co
mpilation.cpp.o
:info:build   "KConfigTest::testQStringUtf8_data()", referenced from:
:info:build       KConfigTest::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) in mocs_co
mpilation.cpp.o
:info:build ld: symbol(s) not found for architecture x86_64
```

[main.log](https://github.com/RJVB/macstrop/files/3475505/main.log)

**Comment by Tatsh** [comment]
This is compiling against `qt5-kde-devel`.

**Comment by RJVB** [comment]
OK, I understand. I missed the fact that there's a kconfigtest.h header which declares the slots. That means a bit more subtle surgery is needed.

BTW, if you run into issues with other frameworks, check them for a +qt59kde variant, which is supposed to enable codepaths relying on the Qt 5.10 stuff I backported into qt5-kde-devel . Both should work of course (with and without the variant, I mean).
