### ISSUE TITLE
Error: Processing of port xz failed

### ISSUE THREAD

**Issue by CodeTourist** [RJVB/macstrop#6]
Hello.
I have a problem with installing the xz port. The MacPorts installation is fresh (no port installed). When I include site-ports to sources.conf and try to install xz, I get this:
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port xz failed

Looks like a circular dependence (the log file is attached).

[main.log.txt](https://github.com/RJVB/macstrop/files/1082979/main.log.txt)

**Comment by RJVB** [comment]
Hi,

You're right, that's a circular dependency on autoconf I never noticed because I had that port installed well before I made my tweaked xz port.

I've pushed an update that will hopefully address the issue.

Can you tell me if you have a version of the autoreconf installed by the system or Xcode on your version of the OS?

Side-note: in case you found my repo because of its KF5 ports, please be aware I'm in the middle of upgrading part of them. Check the commit log to see confirmation that the KF5 Applications upgrade to 17.04.2 has been completed before installing any of those ports, just to be sure.

**Comment by CodeTourist** [comment]
Thank you for the reply!

> You're right, that's a circular dependency on autoconf I never noticed because I had that port installed well before I made my tweaked xz port.

Yes, that was what I thought and that was how I avoided the problem myself. Thought it would be good to let you know anyway.

> Can you tell me if you have a version of the autoreconf installed by the system or Xcode on your version of the OS?

Apparently I don't have it.

> Side-note: in case you found my repo because of its KF5 ports, please be aware I'm in the middle of upgrading part of them. Check the commit log to see confirmation that the KF5 Applications upgrade to 17.04.2 has been completed before installing any of those ports, just to be sure.

I have been trying to build kf5-kate. With no success though.

**Comment by RJVB** [comment]
On Sunday June 18 2017 04:05:18 CodeTourist wrote:

> Yes, that was what I thought and that was how I avoided the problem myself. Thought it would be good to let you know anyway.

Indeed. Thanks again.

> I have been trying to build kf5-kate. With no success though.

Hmmm, I'll leave it to you to decide if and when you want to file another ticket for that but I hope it was just a matter of things being in flush.

**Comment by CodeTourist** [comment]
> I've pushed an update that will hopefully address the issue.

Well, since I do not have automake installed by default, now I get complaints about it. I do not know whether it is a feature or a bug. But I do not encounter this while installing xz from the official port tree.

> Hmmm, I'll leave it to you to decide if and when you want to file another ticket for that but I hope it was just a matter of things being in flush.

With the latest version of the repository I have managed to build Kate. However, I have an issue with icons like for saving file etc, they're simply missing. Do you have an idea why this might happen? kf5-breeze-icons is installed.

**Comment by RJVB** [comment]
On Sunday June 18 2017 12:52:23 CodeTourist wrote:

> Well, since I do not have automake installed by default, now I get complaints about it. I do not know whether it is a feature or a bug. But I do not encounter this while installing xz from the official port tree.

You get a complaint from port:xz ? Can you copy the exact message, please? A priori you should only get an *error* when you try to install the +relocatable variant, and autoconf isn't installed.

> With the latest version of the repository I have managed to build Kate. However, I have an issue with icons like for saving file etc, they're simply missing. Do you have an idea why this might happen? kf5-breeze-icons is installed.

Can you try installing ciment-icons +OSXdg as well as port:kf5-osx-integration-devel ? That should result in icons being shown. The reason you're not getting them is probably 2-fold:

- Breeze is not the default icon theme (in my packaging at least): it looks too much out of place to be the default
- qt5-kde does NOT have a patch to set the icon theme search path by default.

I'm still debating how I'm going to set things up for a proper out-of-the box experience.

**Comment by CodeTourist** [comment]
> You get a complaint from port:xz ? Can you copy the exact message, please? A priori you should only get an *error* when you try to install the +relocatable variant, and autoconf isn't installed.

I do not specify any variants. The log is here:
[main.log.txt](https://github.com/RJVB/macstrop/files/1086200/main.log.txt)

> Can you try installing ciment-icons +OSXdg as well as port:kf5-osx-integration-devel ? That should result in icons being shown.

Thanks for the tips! I have not managed to build kf5-osx-integration-devel though. I'm getting an error: Could not resolve SDK Path for 'macosx10.11'. Trying to figure out what's going on.

**Comment by RJVB** [comment]
>[main.log.txt](https://github.com/RJVB/macstrop/files/1086200/main.log.txt)

Ah, thanks. The error was about automake, not autoconf, and due to the fact I was touching a file without needing to.

>Thanks for the tips! I have not managed to build kf5-osx-integration-devel though. I'm getting an error: Could not resolve SDK Path for 'macosx10.11'. Trying to figure out what's going on.

Again, I'd need a full log to see where that comes from. I have a hunch, but don't understand. You're running OSX 10.11 so you must have the sdk.

What does `fgrep -i macosx10. -R /opt/local/share/qt5/mkspecs/` print for you?

**Comment by CodeTourist** [comment]
> Ah, thanks. The error was about automake, not autoconf, and due to the fact I was touching a file without needing to.

Thanks for fixing it. Now it works. I think this issue may be closed. I'll open a new one related to kf5 ports.
