### ISSUE TITLE
libgcc fails to build

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#61]
[Portfile](https://github.com/RJVB/macstrop/blob/master/lang/gcc7/Portfile)
[main.log](https://github.com/RJVB/macstrop/files/3490629/main.log)

**Comment by RJVB** [comment]
Sorry for the backlog, I was on a trip so could only address issues during rare moments of "free" time. I'll be trying to catch up over the coming days.

**Comment by Tatsh** [comment]
Well for this issue, while there is a problem with libgcc, it doesn't affect me. I don't know why libgcc8/libgcc was requested on my system. There are no packages depending on libgcc8.

**Comment by RJVB** [comment]
You don't have anything that depends on libgcc either? I'm doing some maintenance on my port:gcc7 but it's all a bit guessing from the files you attached to this ticket (they don't show the real error, AFAICT).
