### ISSUE TITLE
portmidi source download issue

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#62]
Over at SF I guess they only keep snapshots for so long. To get the portmidi port to work I had to go to https://sourceforge.net/p/portmedia/code/HEAD/tree/ and click *Download Snapshot*. Then I had to update hashes in the Portfile or it won't work. Right now the port will work with this change:

```diff
diff --git a/audio/portmidi/Portfile b/audio/portmidi/Portfile
index ea12a312..4a4b82fc 100644
--- a/audio/portmidi/Portfile
+++ b/audio/portmidi/Portfile
@@ -22,8 +22,8 @@ dist_subdir         portmedia
 distname            ${dist_subdir}-code-r${version}
 use_zip             yes
 
-checksums           rmd160  04956d5cae5ed4468cb54fd39c35ed0b810bc20b \
-                    sha256  b8f6e06b2a55179ca297258dbe888a51725126be9f2b5013538f92b723de7f1f
+checksums           rmd160  ac406d03a9e401b3d9c9dfa2aa43cdd4e1719de0 \
+                    sha256  76a5acede24fe3096d2b8c233d74fa5fb26a3fa8fa6bed9e7bf6a3c9d8716d29
 #                     size    1342298
 
 worksrcdir          ${distname}/${name}/trunk

```

The next time they delete the snapshot this will have to updated again. Perhaps there's a better way like putting the binary here under releases and linking to that (kind of a hack but still an improvement)? Or you can check out over HTTPS with SVN?

Over on Gentoo they are using version 217 rather than 234 and it must be working fine. They pull it in over the mirror URL that always works for a release as opposed to their snapshot generator.

https://download.sourceforge.net/portmedia/portmidi-src-217.zip (they do a user-agent scan on this URL; must be cURL or wget or similar to get the file)

**Comment by RJVB** [comment]
Fixed by fetching over SVN.
