### ISSUE TITLE
Cannot use Chromecast with VLC

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#63]
The version from this repo can see my Chromecast but it does not connect (Playback -> Renderer menu). Based on the log it seems a module is missing.

The version from VLC website works fine.

>main debug: requesting art for new input thread
main debug: using sout chain=`chromecast{ip=93284a4b-8e64-ead6-e61c-5de4343ee6b6.local.,port=8009}'
main debug: stream=`chromecast'
main debug: looking for sout stream module matching "chromecast": 20 candidates
main debug: no sout stream modules matched
main debug: destroying chain... (name=(null))
main debug: looking for meta fetcher module matching "any": 1 candidates
main debug: destroying chain done
main error: stream chain failed for `chromecast{ip=93284a4b-8e64-ead6-e61c-5de4343ee6b6.local.,port=8009}'
main error: cannot start stream output instance, aborting

**Comment by RJVB** [comment]
This port is functionally identical to the mainstream one, so would you mind reporting the issue on Trac? Maybe someone there will chime in and point out which module is missing due to what dependencies not being available...

**Comment by Tatsh** [comment]
Sent it to the mailing list as the website seems to be down.
