### ISSUE TITLE
Failed to patch qt5-kde

### ISSUE THREAD

**Issue by CodeTourist** [RJVB/macstrop#7]
I suppose lbzip2 should be in the dependency list for qt5-kde. Otherwise, I have this:

:error:patch Failed to patch qt5-kde: command execution failed
:debug:patch Error code: CHILDSTATUS 99847 1
:debug:patch Backtrace: command execution failed
:debug:patch     while executing
:debug:patch "system {*}$notty {*}$nice $fullcmdstring"
:debug:patch     invoked from within
:debug:patch "command_exec patch "" "< '$patch'""
:debug:patch     (procedure "portpatch::patch_main" line 33)
:debug:patch     invoked from within
:debug:patch "$procedure $targetname"
:debug:patch Failed to locate 'lbzip2' in path: '/testports/bin:/testports/sbin:/bin:/sbin:/usr/bin:/usr/sbin' or at its MacPorts configuration time location, did you move it?

**Comment by RJVB** [comment]
What MacPorts version do you have installed?! The patch_main procedure your log extract references tries to execute $bzcat, which is set to the result of an internal lookup procedure. If that returns lbzip2 instead of bzip2 when you don't have the former installed, that'd be a bug in MacPorts "base".

Please upload the full log because I don't even understand why you'd be needing any form of bzip2 for patching qt5-kde . There are no compressed patchfiles for that port.

I did find an issue with the latest version of an upstream patch, so please pull the repo before trying again.

**Comment by CodeTourist** [comment]
> What MacPorts version do you have installed?! The patch_main procedure your log extract references tries to execute $bzcat, which is set to the result of an internal lookup procedure. If that returns lbzip2 instead of bzip2 when you don't have the former installed, that'd be a bug in MacPorts "base".

It's 2.4.1.

> Please upload the full log because I don't even understand why you'd be needing any form of bzip2 for patching qt5-kde . There are no compressed patchfiles for that port.

version:1
:debug:main Privilege de-escalation not attempted as not running as root.
:debug:main Executing org.macports.main (qt5-kde)
:debug:main Privilege de-escalation not attempted as not running as root.
:debug:main Skipping completed org.macports.archivefetch (qt5-kde)
:debug:main Privilege de-escalation not attempted as not running as root.
:debug:main Skipping completed org.macports.fetch (qt5-kde)
:debug:main Privilege de-escalation not attempted as not running as root.
:debug:main Skipping completed org.macports.checksum (qt5-kde)
:debug:main Privilege de-escalation not attempted as not running as root.
:debug:main Skipping completed org.macports.extract (qt5-kde)
:debug:main Privilege de-escalation not attempted as not running as root.
:debug:patch patch phase started at Sun Jun 18 15:16:06 CEST 2017
:debug:patch Executing org.macports.patch (qt5-kde)
:notice:patch --->  Applying patches to qt5-kde
:info:patch --->  Applying patch-machtest.diff
:debug:patch Environment: 
:debug:patch CC_PRINT_OPTIONS='YES'
:debug:patch CC_PRINT_OPTIONS_FILE='/testports/var/macports/build/_testports_site-ports_aqua_qt5-kde/qt5-kde/work/.CC_PRINT_OPTIONS'
:debug:patch CPATH='/testports/include'
:debug:patch LIBRARY_PATH='/testports/lib'
:debug:patch MACOSX_DEPLOYMENT_TARGET='10.11'
:info:patch Executing:  cd "/testports/var/macports/build/_testports_site-ports_aqua_qt5-kde/qt5-kde/work/qt-everywhere-opensource-src-5.8.0" && /usr/bin/patch -Np1 < '/testports/site-ports/aqua/qt5-kde/files/patch-machtest.diff'
:debug:patch system:  cd "/testports/var/macports/build/_testports_site-ports_aqua_qt5-kde/qt5-kde/work/qt-everywhere-opensource-src-5.8.0" && /usr/bin/patch -Np1 < '/testports/site-ports/aqua/qt5-kde/files/patch-machtest.diff'
:info:patch patching file qtbase/tests/auto/corelib/plugin/qpluginloader/machtest/machtest.pro
:info:patch Reversed (or previously applied) patch detected!  Skipping patch.
:info:patch 1 out of 1 hunk ignored -- saving rejects to file qtbase/tests/auto/corelib/plugin/qpluginloader/machtest/machtest.pro.rej
:info:patch Command failed:  cd "/testports/var/macports/build/_testports_site-ports_aqua_qt5-kde/qt5-kde/work/qt-everywhere-opensource-src-5.8.0" && /usr/bin/patch -Np1 < '/testports/site-ports/aqua/qt5-kde/files/patch-machtest.diff'
:info:patch Exit code: 1
:error:patch Failed to patch qt5-kde: command execution failed
:debug:patch Error code: CHILDSTATUS 70303 1
:debug:patch Backtrace: command execution failed
:debug:patch     while executing
:debug:patch "system {*}$notty {*}$nice $fullcmdstring"
:debug:patch     invoked from within
:debug:patch "command_exec patch "" "< '$patch'""
:debug:patch     (procedure "portpatch::patch_main" line 33)
:debug:patch     invoked from within
:debug:patch "$procedure $targetname"
:debug:patch Failed to locate 'lbzip2' in path: '/testports/bin:/testports/sbin:/bin:/sbin:/usr/bin:/usr/sbin' or at its MacPorts configuration time location, did you move it?
:debug:patch     while executing
:debug:patch "error "$eMessage or at its MacPorts configuration time location, did you move it?""
:debug:patch     invoked from within
:debug:patch "try -pass_signal {
:debug:patch             set cmd_path [macports::binaryInPath $prog]
:debug:patch             return $cmd_path
:debug:patch         } catch {{*} eCode eMessage} {
:debug:patch        ..."
:debug:patch     (procedure "macports::findBinary" line 5)
:error:patch See /testports/var/macports/logs/_testports_site-ports_aqua_qt5-kde/qt5-kde/main.log for details.

**Comment by RJVB** [comment]
On Sunday June 18 2017 06:21:07 CodeTourist wrote:
>:debug:patch system:  cd "/testports/var/macports/build/_testports_site-ports_aqua_qt5-kde/qt5-kde/work/qt-everywhere-opensource-src-5.8.0" && /usr/bin/patch -Np1 < '/testports/site-ports/aqua/qt5-kde/files/patch-machtest.diff'
>:info:patch patching file qtbase/tests/auto/corelib/plugin/qpluginloader/machtest/machtest.pro
>:info:patch Reversed (or previously applied) patch detected!  Skipping patch.
>:info:patch 1 out of 1 hunk ignored -- saving rejects to file qtbase/tests/auto/corelib/plugin/qpluginloader/machtest/machtest.pro.rej
>:info:patch Command failed:  cd "/testports/var/macports/build/_testports_site-ports_aqua_qt5-kde/qt5-kde/work/qt-everywhere-opensource-src-5.8.0" && /usr/bin/patch -Np1 < '/testports/site-ports/aqua/qt5-kde/files/patch-machtest.diff'
>:info:patch Exit code: 1

Sorry, I should have reminded you to do `port clean qt5-kde` before trying again... 
The log doesn't make sense to me like this, hopefully it'll be more informative after doing a clean.

I take it you didn't install port:lbzip2 yourself? I don't, and cannot reproduce your issue on any of my machines.

**Comment by CodeTourist** [comment]
> Sorry, I should have reminded you to do `port clean qt5-kde` before trying again...

Thanks for ponting this out. I do not know the reason but after having it cleaned the problem is gone. I think that the issue may be closed.

**Comment by RJVB** [comment]
Sh** happens ;)
