### ISSUE TITLE
Audacity fails to build

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#77]
Log: 
[main.log.gz](https://github.com/RJVB/macstrop/files/3914013/main.log.gz)

**Comment by RJVB** [comment]
>[main.log.gz](https://github.com/RJVB/macstrop/files/3914013/main.log.gz)

Did you refresh the port tree and is that the right log? It still shows a patch being applied twice, and I fixed that as far as I can tell.

**Comment by Tatsh** [comment]
Pretty sure it is up-to-date but I can check again later. The main error is this:

```
:info:build prefs/PrefsDialog.cpp:590:36: error: member access into incomplete type 'wxTreeCtrl'
:info:build          mCategories->GetTreeCtrl()->SetName(_("Category"));
```

**Comment by Tatsh** [comment]
That was up-to-date. Got the same error again.

**Comment by RJVB** [comment]
Well, apologies, I didn't look beyond the 1st (patch) error message in the log so didn't notice the compile error. Normally they're recreated when you relaunch a build, but this one apparently wasn't.
