### ISSUE TITLE
macOS - Quassel Client missing icon, localised name

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#78]
In the past the icon was present in the app bundle. This wouldn't be a big deal but it shows a generic app icon in the dock when the app is not running.

<img width="397" alt="MacOS-2019-12-08 11-32-58" src="https://user-images.githubusercontent.com/724848/70392480-8388b580-19ae-11ea-84fc-fb2330bb88ed.png">

Also there should be a localised name or the app bundle name should simply be `Quassel Client.app`.

**Comment by RJVB** [comment]
This has been coming for a while: I don't have time enough to maintain ports I don't use myself esp. if there's an equivalent among my ports (kf5-konversation). Retiring my copy, sorry.

**Comment by RJVB** [comment]
PS: my own build from March this year also doesn't have an embedded icon, from how far back into the past does your memory come?!

**Comment by Tatsh** [comment]
Oddly enough, I rebuilt after copying your Portfile to my port set and it now has an icon and the proper name.

<img width="717" alt="Resources-2019-12-08 23-19-32" src="https://user-images.githubusercontent.com/724848/70407169-3689fb00-1a11-11ea-810c-7db6f2c21439.png">

**Comment by RJVB** [comment]
Did you install with the +kde variant? That variant sets `WITH_BUNDLED_ICONS=OFF`, which a priori means that no icons will be embedded into the Qt resource, but which in hindsight could also mean no bundle icon will be installed.
