### ISSUE TITLE
Can not install qt5-kde on Catalina

### ISSUE THREAD

**Issue by 21stcaveman** [RJVB/macstrop#79]
Hi, qt5-kde install fails to fetch the source tar file :

--->  Computing dependencies for qt5-kde
--->  Fetching distfiles for qt5-kde
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://distfiles.macports.org/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://ywg.ca.distfiles.macports.org/mirror/macports/distfiles/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from http://ykf.ca.distfiles.macports.org/MacPorts/mpdistfiles/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://kmq.jp.distfiles.macports.org/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://mse.uk.distfiles.macports.org/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://lil.fr.distfiles.macports.org/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://cph.dk.distfiles.macports.org/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://nue.de.distfiles.macports.org/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from http://aarnet.au.distfiles.macports.org/pub/macports/distfiles/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from http://cjj.kr.distfiles.macports.org/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from http://fco.it.distfiles.macports.org/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://jnb.za.distfiles.macports.org/distfiles/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from http://jog.id.distfiles.macports.org/macports/distfiles/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from https://pek.cn.distfiles.macports.org/macports/distfiles/qt5
--->  Attempting to fetch qt-everywhere-opensource-src-5.9.8.tar.xz from http://download.qt.io/official_releases/qt/5/5.9.8/single/
Error: Failed to fetch qt5-kde: The requested URL returned error: 404 Not Found

Any pointers how to fix this?

**Comment by 21stcaveman** [comment]
tried this :
https://github.com/RJVB/macstrop/issues/54#issuecomment-518942860

and it did fix the download URL issue, that does not seem like a real fix though. Or is it?

**Comment by 21stcaveman** [comment]
After commit 8871283, now portindex fails completely to add qt5-kde and qt5-kde-devel ports with :

Failed to parse file aqua/qt5-kde-devel/Portfile: wrong # args: should be "qt5.active_branch"
Failed to parse file aqua/qt5-kde/Portfile: wrong # args: should be "qt5.active_branch"

**Comment by RJVB** [comment]
My bad, that happens when I get distracted and forget to include a file that has the crucial change... Should be all good now.

**Comment by 21stcaveman** [comment]
Perfect, that did resolve the issue. Thank you. Building qt5-kde still fails though. It builds all the way to cmake, and then it fails with no error. Trying to install it again, I get this :

sudo port install qt5-kde
--->  Computing dependencies for qt5-kde
The following dependencies will be installed: 
 cmake
 lcms2
 libarchive
 libmng
 tiff
 zstd
Continue? [Y/n]: y
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port qt5-kde failed

looking into the main.log, it has a bunch of dependencies, for which it can not (find receipt). Some of them are :
qt3
qt3-mac
qt5-base
qt-kde-devel
...
tiff
libmng
zstd
cmake
cmake-devel
lcms2

Any pointers? Is this a macports bug?

**Comment by RJVB** [comment]
On Wednesday October 21 2020 10:20:20 Hamid Maadani wrote:

>--->  Computing dependencies for qt5-kde
>The following dependencies will be installed: 
...
>Continue? [Y/n]: y
>Error: Follow https://guide.macports.org/#project.tickets to report a bug.
>Error: Processing of port qt5-kde failed

There should be a more explanatory error message there.
>
>looking into the main.log, it has a bunch of dependencies, for which it can not (find receipt). Some of them are :

>qt-kde-devel

qt-kde-devel, without a digit?!


>qt3
>qt3-mac
>qt5-base

>cmake
>cmake-devel

Both? That shouldn't happen!

A priori cmake is not a direct dependency for Qt, btw, but dependencies have dependencies too. I think the best way forward here is to take the list of dependencies that are indicated as required, and install each manually. Or you can look at the actual dependencies listed via `port info qt5-kde` and install the missing ones from that list. That might solve the issue, or if not it should at least allow me to understand what goes wrong. It's possible that one of the (in)direct dependencies needs an update ... but I don't see how it could lead to attempts to install Qt3...

R.

**Comment by 21stcaveman** [comment]
I agree, there should be a more explanatory message. Unfortunately, there is not!
That's my bad, it was qt5-kde-dev.

so, I ran `port info qt5-kde`, and I got :
Extract Dependencies: xz
Build Dependencies:   pkgconfig
Library Dependencies: sqlite3, zlib, libpng, jpeg, freetype, fontconfig, dbus, openssl, tiff, libmng, glib2, icu, pcre2, mariadb, harfbuzz

I ran them one by one, and all are already installed, but :
tiff, libmng

trying to manually install them :

sudo port install libmng 
--->  Computing dependencies for libmng
The following dependencies will be installed: 
 cmake
 lcms2
 libarchive
 tiff
 zstd
Continue? [Y/n]: y
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port libmng failed

sudo port install tiff  
--->  Computing dependencies for tiff
The following dependencies will be installed: 
 cmake
 libarchive
 zstd
Continue? [Y/n]: y
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port tiff failed

As you can see, no explanation on why it fails, and both depend on cmake, libarchive, and zstd. Trying to manually install either one of these 3 also gets me exactly the same result :

sudo port install cmake
--->  Computing dependencies for cmake
The following dependencies will be installed: 
 cmake
 libarchive
 zstd
Continue? [Y/n]: y
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port cmake failed

It's almost as if those 3 depend on each other, and create a circular dependency failure!

**Comment by RJVB** [comment]
On Wednesday October 21 2020 11:10:12 Hamid Maadani wrote:

>It's almost as if those 3 depend on each other, and create a circular dependency failure!

Ahhh, good eyes! That's exactly the problem. My port:zstd uses cmake to build, and since I had cmake installed before zstd I never discovered that this led to a circular dependency.

Can you pull and try again, please?

R.

**Comment by 21stcaveman** [comment]
Perfect, that did fix the issue! Thank you for putting time on this.

Off to build kf5-dolphin :)
