### ISSUE TITLE
Activation of dbus +no_root fails

### ISSUE THREAD

**Issue by CodeTourist** [RJVB/macstrop#8]
I'm getting this error while trying to install dbus (no_root variant):
:error:activate Failed to activate dbus: could not set owner for file "/testports2/libexec/dbus-daemon-launch-helper": not owner
[main.log.txt](https://github.com/RJVB/macstrop/files/1100504/main.log.txt)

And one more thing: why do you have dbus 1.10.12 which is older than the one in the official port tree (1.10.18)?

**Comment by RJVB** [comment]
Did you use sudo? Could you please drop the no_root variant, I don't think it's a good idea to use it.

Another thing, do you think you'll ever be using commands that require the system dbus and privilege escalation? The answer that question is probably "no" if you don't really know what DBus is and you'll only be using desktop applications that run as a normal user (= 99.99% of the time).

I see I should update my port ...

**Comment by CodeTourist** [comment]
> Did you use sudo? Could you please drop the no_root variant, I don't think it's a good idea to use it.

I do not use sudo for MacPorts in general. I mean ports are installed without root privileges into a folder with rw permissions for the user. If I dropped no_root, I would get an error that dbus could not copy its file into LaunchDaemons (obviously).

> Another thing, do you think you'll ever be using commands that require the system dbus and privilege escalation? The answer that question is probably "no" if you don't really know what DBus is and you'll only be using desktop applications that run as a normal user (= 99.99% of the time).

I do not plan to make any use of dbus on Mac. I would happily avoid it completely, but since these are apps written for Linux, I need to have it.

> I see I should update my port ...

Well, never mind. In the end, this error does not really affect usage of other ports (as far as I can tell). I do not have this issue with dbus from the official port tree, though.

**Comment by RJVB** [comment]
On Sunday June 25 2017 13:40:26 CodeTourist wrote:

> > Did you use sudo? Could you please drop the no_root variant, I don't think it's a good idea to use it.
> 
> I do not use sudo for MacPorts in general. 

That's not a supported way of using MacPorts, I'm afraid. But I've made a small change to my port:dbus which should prevent the error from happening.

> I do not plan to make any use of dbus on Mac.
> I would happily avoid it completely, but since these are apps written for Linux, I need to have it.

It's not you who'll be using dbus, but certain applications.
Dbus provides a desktop-centred inter-process communications protocol (IPC). Many view it as "alien" outside of Linux, but in reality it's about the only cross-platform desktop bus that exists (and that serves a purpose for which there's no true native alternative on Mac or MSWin, to my knowledge).

> > I do not have this issue with dbus from the official port tree, though.

No, that's because the official port lacks support for a properly functioning system dbus.

**Comment by CodeTourist** [comment]
> That's not a supported way of using MacPorts, I'm afraid.

Well, MacPorts allow installation to a custom folder and support no_root variant. I have not had issues so far (except dbus).

> But I've made a small change to my port:dbus which should prevent the error from happening.

Thanks.

> Many view it as "alien" outside of Linux, but in reality it's about the only cross-platform desktop bus that exists...

Formally, yes. But DBus is not used by native applications on Mac and Windows. Even devs from *BSD community do not seem to like it. So, only Linux.

> No, that's because the official port lacks support for a properly functioning system dbus.

Oh, interesting.

**Comment by RJVB** [comment]
On Sunday June 25 2017 14:30:24 CodeTourist wrote:

>Well, MacPorts allow installation to a custom folder and support no_root variant. I have not had issues so far (except dbus).

What I mean is that the intended and supported use is to run `sudo port install foo`. I'm not sure of the actual purpose of the `no_root` variant, but I think the description would mention it if it existed to allow installing ports without root privileges.

The dbus daemon you use under normal circumstances runs as any other of your own processes.

**Comment by CodeTourist** [comment]
> But I've made a small change to my port:dbus which should prevent the error from happening.

It works now. Thanks.
