### ISSUE TITLE
kf5-dolphin on Big Sur

### ISSUE THREAD

**Issue by 21stcaveman** [RJVB/macstrop#82]
When trying to install kf5-dolphin on macos big sur (MacPorts 2.7.1), it fails with :

Error: Unable to execute port: can't read "destroot.pre_args": can't read "destroot.cmd": can't read "python.bin": can't read "python.prefix": can't read "python.branch": can't read "python.version": can't read "name": no such variable

Am I missing something? or is this a new requirement? same Portfile used to work fine on Catalina.

**Comment by RJVB** [comment]
On Monday June 28 2021 12:51:59 Hamid wrote:

>Am I missing something? or is this a new requirement? same Portfile used to work fine on Catalina.

Are you sure it was the same Portfile (which doesn't invoke anything python-related directly so it must come from a PortGroup)?

**Comment by 21stcaveman** [comment]
Positive on the Portfile. Looking at my notes however, seems like kf5-dolphin-devel worked on Catalina, not kf5-dolphin itself.

Just tried `sudo port install kf5-dolphin-devel`, which failed with the same error.
Trying kf5-dolphin-devel step by step seems to work though (fetch, extract, configure, ... instead of install).
I'll let you know if I can build it that way.

**Comment by RJVB** [comment]
On Monday June 28 2021 14:54:49 Hamid wrote:
>Positive on the Portfile. Looking at my notes however, seems like kf5-dolphin-devel worked on Catalina, not kf5-dolphin itself.

Ah, that's possible. I think I haven't build kf5-dolphin in a while.

And you're right, it must be something the port does differently than its (large) number of KF5 dependents.  Still, it doesn't set any of the `destroot.` variables that you get errors about... In fact, there isn't a single Portfile in my KF5 tree that uses `destroot.pre_args`. Keep me posted please!

**Comment by 21stcaveman** [comment]
Ok, so, got all dependencies installed (new system, took a while. Had a small issue with qgpgme, and had to add breeze and osx-integration as dependencies). All stages work, up to destroot.
When running `sudo port destroot kf5-dolphin-devel`, I get :

Error: Unable to execute port: can't read "destroot.pre_args": can't read "destroot.cmd": can't read "python.bin": can't read "python.prefix": can't read "python.branch": can't read "python.version": can't read "name": no such variable.

I have set the new system up, with Portgroups, according to your instructions. Not sure where to look to find the culprit at this point. Any suggestions?

**Comment by RJVB** [comment]
>I have set the new system up, with Portgroups, according to your instructions. Not sure where to look to find the culprit at this point. Any suggestions?

This is going to be tricky to debug for me too. Did you keep the logfile? If you actually executed `port destroot` last you can upload the entire logfile here, otherwise please extract just the lines that start with `:debug:destroot` . I'll see if I can trace back the origin of the issue in there.

- I presume you're not building with +universal?
- have you tried any other KF5 port that installs an application, like kf5-kwalletmanager?

Also, where and why did you add the breeze and osx-integration dependencies?

**Comment by 21stcaveman** [comment]
I appreciate your time, Rene.

I have removed the log file, and ran just the destroot command. Log file attached is for that command only, however, it only shows :debug:main and no :debug:destroot.
[main.log](https://github.com/RJVB/macstrop/files/6734772/main.log)

I am not building with +universal, correct.
I have installed kf5-kate, kf5-konsole and kf5-okular successfully, without running into this issue.
This issue only happens if I try kf5-dolphin-devel , or kf5-krdc. Not sure what the two have in common, that is different from others.

**Comment by RJVB** [comment]
Wow, looking at the backtrace it would seem the issue is not with my port, but with a dependency of avahi which is itself a runtime dependency of kf5-kdnssd (a dependency of kf5-kio-extras). The dependency in question if py39-gobject3 ... and indeed, I get the same error if I even try `port info` on that port.


The weird thing is that you must have gotten those dependencies installed when you installed kf5-kio-extras ... but then again maybe you didn't install that port yet?

The real culprit is in the python PG. I'm going have to ask around!

**Comment by RJVB** [comment]
I pushed a workaround. Can you try the destroot step again please?

**Comment by 21stcaveman** [comment]
Seems to have worked, in terms of going past the destroot warnings. However, now kf5-kio-extras is throwing a linker error.

[ 76%] Linking CXX shared module ../bin/audiothumbnail.so
cd /opt/local/var/macports/build/_opt_local_site-ports_kf5_kf5-kio-extras/kf5-kio-extras/work/build/thumbnail && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/audiothumbnail.dir/link.txt --verbose=1
/usr/bin/clang++ -pipe -Os -DNDEBUG -DQT_USE_EXTSTANDARDPATHS -DQT_EXTSTANDARDPATHS_ALT_DEFAULT=true -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -fno-operator-names -fno-exceptions -DQT_NO_EXCEPTIONS -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -mmacosx-version-min=11.0 -bundle -Wl,-headerpad_max_install_names -multiply_defined suppress -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -o ../bin/audiothumbnail.so CMakeFiles/audiothumbnail.dir/audiothumbnail_autogen/mocs_compilation.cpp.o CMakeFiles/audiothumbnail.dir/audiocreator.cpp.o  -Wl,-rpath,/opt/local/lib /opt/local/lib/libKF5KIOWidgets.5.60.0.dylib /opt/local/lib/libKF5KIOCore.5.60.0.dylib /opt/local/lib/libKF5JobWidgets.5.60.0.dylib /opt/local/lib/libKF5Service.5.60.0.dylib /opt/local/libexec/qt5/Library/Frameworks/QtNetwork.framework/QtNetwork /opt/local/lib/libKF5Completion.5.60.0.dylib /opt/local/libexec/qt5/Library/Frameworks/QtConcurrent.framework/QtConcurrent /opt/local/lib/libKF5WidgetsAddons.5.60.0.dylib /opt/local/lib/libKF5ConfigCore.5.60.0.dylib /opt/local/libexec/qt5/Library/Frameworks/QtWidgets.framework/QtWidgets /opt/local/lib/libKF5CoreAddons.5.60.0.dylib /opt/local/libexec/qt5/Library/Frameworks/QtDBus.framework/QtDBus /opt/local/libexec/qt5/Library/Frameworks/QtGui.framework/QtGui /opt/local/libexec/qt5/Library/Frameworks/QtCore.framework/QtCore 
Undefined symbols for architecture x86_64:
  "TagLib::ByteVector::ByteVector(char const*)", referenced from:
      AudioCreator::create(QString const&, int, int, QImage&) in audiocreator.cpp.o
  "TagLib::ByteVector::ByteVector(TagLib::ByteVector const&)", referenced from:
...

**Comment by RJVB** [comment]
On Tuesday June 29 2021 17:06:29 Hamid wrote:
>Seems to have worked, in terms of going past the destroot warnings.

Great, thanks for confirming!

>However, now kf5-kio-extras is throwing a linker error.
...
>Undefined symbols for architecture x86_64:
^^^ Didn't you say you were building on an M1 CPU?!

>  "TagLib::ByteVector::ByteVector(char const*)", referenced from:

I just rebuilt kf5-kio-extras against the latest taglib on my end (an actual x86_64 system) and didn't get any errors. I'll admit that I have no idea what MacPorts does when a port has `supported_archs x86_64` and you build it on arm64 and AFAICT none of the ports in my tree that should be relevant here set it, but you may want to check if you're not dealing with a cross-architecture mix. You can run x84_64 code on an M1 but I'd be really impressed if a single process can run code of both architectures.

**Comment by 21stcaveman** [comment]
> ^^^ Didn't you say you were building on an M1 CPU?!

I am not. My system is running on an Intel i7 chip, not M1.
Interesting that you could build kio-extras. I have taglib 1.12.0 installed. Can you please confirm that's the version you have?

**Comment by RJVB** [comment]
>Interesting that you could build kio-extras. I have taglib 1.12.0 installed. Can you please confirm that's the version you have?

Yep. Now I must admit that was on Linux (haven't yet had access to my Mac system) but that shouldn't make a difference here.

I have

```
> nm /opt/local/lib/libtag.so | grep -i '_ZN6TagLib10ByteVectorC.EPKc'
00000000000b1170 T _ZN6TagLib10ByteVectorC1EPKc
00000000000b1010 T _ZN6TagLib10ByteVectorC1EPKcj
00000000000b1170 T _ZN6TagLib10ByteVectorC2EPKc
00000000000b1010 T _ZN6TagLib10ByteVectorC2EPKcj

> demangle _ZN6TagLib10ByteVectorC1EPKc _ZN6TagLib10ByteVectorC2EPKc
_ZN6TagLib10ByteVectorC1EPKc -> "TagLib::ByteVector::ByteVector(char const*)"
_ZN6TagLib10ByteVectorC2EPKc -> "TagLib::ByteVector::ByteVector(char const*)"
```

name mangling is the same on Linux and Darwin, so a priori you should be able to run the nm command on your /opt/local/lib/libtag.dylib and get the same results (except for the addresses in the 1st column of course).

**Comment by RJVB** [comment]
OK, I spoke too soon. I don't know what happened, but I can reproduce your issue on my lowly 10.9.5 Mac. Looks simple though: the link to libtag isn't even attempted. I'll see how to fix this, maybe just upgrade the port...

**Comment by 21stcaveman** [comment]
Not sure if github sends email notifications for comment updates, but I have updated my last comment with how I fixed the issue on my system. Maybe that'd help with fixing the port.

**Comment by RJVB** [comment]
Thanks!

I'm working on a small upgrade, to 19.11.90 . Later kio-extras version require kdsoap (whatever that is) and I am not really in the mood to make new ports ATM. This version has the same issue, but it seems to be a problem with the FindTaglib cmake module that is in the kde-extra-cmake-modules port instead of the one that comes with kio-extras. I'll figure something out and let you know when there's an update.

**Comment by 21stcaveman** [comment]
Absolutely, sounds good.

**Comment by RJVB** [comment]
Hi,

I just pushed a kio-extras update to 20.04.3 . This one already required quite a bit of backporting so I'm going to leave it at this for the time being!

**Comment by 21stcaveman** [comment]
Confirmed, I could upgrade kio-extras using `port upgrade outdated` with no issues.

Appreciate all the great work Rene.

**Comment by RJVB** [comment]
Hey,

A thumbs-up that you may want to up the revbump for kio-extras; I fixed a crasher in the text file thumbnail creator.

**Comment by 21stcaveman** [comment]
Acknowledged. Upgraded kio-extras, and all works fine. No issues during upgrade.
