### ISSUE TITLE
Some Portfiles fail to parse

### ISSUE THREAD

**Issue by cooljeanius** [RJVB/macstrop#84]
I'm just getting started with this repo, and saw this after `selfupdate`-ing:
```
Total number of ports parsed:	1331 
Ports successfully parsed:	1328 
Ports failed:			3 
Up-to-date ports skipped:	0
```
Looking back a bit in the output, I can see this:
```
Failed to parse file www/arora/Portfile: invalid command name "qt5.unset_cxxflags"
Failed to parse file www/midori/Portfile: can't set "depends_lib": invalid depspec: depends_run
```
...and a bit further back:
```
Failed to parse file multimedia/qmplay2/Portfile with subport 'qmplay2-x11': unknown component x11
```
There are also a bunch of warnings in the form of:
```
Warning: depends_libs change: path:lib/libQtCore.4.dylib:qt4-mac
Warning: Using the mainstream/official Qt4 portgroup
```
...but those are just warnings and aren't quite as important.

**Comment by cooljeanius** [comment]
Current parse failure:
```
libcxx_from_macstrop@9.0.1
Adding port lang/libcxx
Adding port multimedia/fluidsynth
Warning: Failed to open old entry for qt/qt5, making a new one
Adding port qt/qt5
Adding subport qt5-qtquickcontrols2
Adding subport qt5-qtquickcontrols2-docs
Failed to parse file qt/qt5/Portfile with subport 'qt5-qtbase': can't read "qt_qmake_spec": no such variable
```

**Comment by RJVB** [comment]
On Tuesday December 27 2022 03:13:53 Eric Gallager wrote:

>Failed to parse file qt/qt5/Portfile with subport 'qt5-qtbase': can't read "qt_qmake_spec": no such variable

That looks like you don't have my patch installed that makes "base" read PortGroup files from the current repository first.

Can you `port edit qt5-qtbase` and replace all occurrences of `PortGroup qt5 1.0` with `PortGroup qt5-stock 1.0` and report back, please?

**Comment by cooljeanius** [comment]
> On Tuesday December 27 2022 03:13:53 Eric Gallager wrote: Failed to parse file qt/qt5/Portfile with subport 'qt5-qtbase': can't read "qt_qmake_spec": no such variable
> That looks like you don't have my patch installed that makes "base" read PortGroup files from the current repository first. Can you `port edit qt5-qtbase` and replace all occurrences of `PortGroup qt5 1.0` with `PortGroup qt5-stock 1.0` and report back, please?

Actually never mind, I no longer have this Portfile repository cloned, so I no longer experience this error; I'll close it now...
