### ISSUE TITLE
lzvn has a problem with its archs

### ISSUE THREAD

**Issue by cooljeanius** [RJVB/macstrop#87]
I'm on an x86_64 MBP and get this error when trying to install lzvn from this repository:
```
Error: lzvn cannot be installed for the configured build_arch 'x86_64' because it only supports the arch(s) '{x86_64 arm64}'.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port lzvn failed
```

**Comment by RJVB** [comment]
To be honest, I don't even know why I added the (undoubtedly false) claim for arm64 support, unless Apple somehow incorporated Rosetta in their clang compilers so they can generate arm64 bitcode from amd64 assembly?!
