### ISSUE TITLE
qt5-kde: build issues (Monterey)

### ISSUE THREAD

**Issue by 21stcaveman** [RJVB/macstrop#88]
Two very small issues when building qt5-kde on MacOS 12.0.1:

1. It tries to build ...qt-everywhere-opensource-src-5.9.8/qtscript/src/3rdparty/javascriptcore/version
2. It throws 3 assembly errors for ...qt-everywhere-opensource-src-5.9.8/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/jit/JITStubs.cpp

Just putting this here, until I can make a patch for it.

**Comment by RJVB** [comment]
Thx, waiting for your patch then!

**Comment by 21stcaveman** [comment]
This patch worked :

fix-asm-volatile.patch
`
--- qtscript/src/3rdparty/javascriptcore/JavaScriptCore/jit/JITStubs.cpp
+++ qtscript/src/3rdparty/javascriptcore/JavaScriptCore/jit/JITStubs.cpp
@@ -480,7 +480,7 @@ COMPILE_ASSERT(offsetof(struct JITStackFrame, callFrame) == 0x58, JITStackFrame_
 COMPILE_ASSERT(offsetof(struct JITStackFrame, code) == 0x48, JITStackFrame_code_offset_matches_ctiTrampoline);
 COMPILE_ASSERT(offsetof(struct JITStackFrame, savedRBX) == 0x78, JITStackFrame_stub_argument_space_matches_ctiTrampoline);

-asm volatile (
+asm (
 ".text\n"
 ".globl " SYMBOL_STRING(ctiTrampoline) "\n"
 HIDE_SYMBOL(ctiTrampoline) "\n"
@@ -515,7 +515,7 @@ SYMBOL_STRING(ctiTrampoline) ":" "\n"
     "ret" "\n"
 );

-asm volatile (
+asm (
 ".globl " SYMBOL_STRING(ctiVMThrowTrampoline) "\n"
 HIDE_SYMBOL(ctiVMThrowTrampoline) "\n"
 SYMBOL_STRING(ctiVMThrowTrampoline) ":" "\n"
@@ -531,7 +531,7 @@ SYMBOL_STRING(ctiVMThrowTrampoline) ":" "\n"
     "ret" "\n"
 );

-asm volatile (
+asm (
 ".globl " SYMBOL_STRING(ctiOpThrowNotCaught) "\n"
 HIDE_SYMBOL(ctiOpThrowNotCaught) "\n"
 SYMBOL_STRING(ctiOpThrowNotCaught) ":" "\n"
--- qtscript/src/3rdparty/javascriptcore/VERSION
+++ qtscript/src/3rdparty/javascriptcore/VERSION
@@ -1,3 +1,4 @@
+/*
 This is a snapshot of JavaScriptCore from

         git://gitorious.org/qtwebkit/qtwebkit.git
@@ -9,3 +10,4 @@ The commit imported was from the
 and has the sha1 checksum

         3ab0f621048fbeb480b687a28ed31d92d8506150
+*/
`

I tried to put it in the right place and sumbit a commit, but got a headache trying to find where the patch should go in the Portfile :)) I'll leave that part to you, please.

**Comment by RJVB** [comment]
Oops, I missed your patch, was on vacation. I'll commit it as soon as I can, thanks again!

**Comment by 21stcaveman** [comment]
No worries, and thank you :)
