### ISSUE TITLE
git clone times out for attr

### ISSUE THREAD

**Issue by 21stcaveman** [RJVB/macstrop#93]
git clone times out for 'attr', until I switch master url to https (https://github.com/RJVB/attr)
not sure if this is system specific, or some new github restriction. Just putting it out there, please close if not relevant.

**Comment by 21stcaveman** [comment]
well, guess [this](https://github.blog/2021-09-01-improving-git-protocol-security-github/) answers that question. 'git://' URLs are not supported by github anymore.

Same applies to 'acl' port.

**Comment by 21stcaveman** [comment]
Hi,

seems likepatch-darwin.diff can't be applied to attr anymore:

`:info:patch Command failed:  cd "/opt/local/var/macports/build/_opt_local_site-ports_sysutils_attr/attr/work/attr-git" && /usr/bin/patch -Np1 < '/opt/local/site-ports/sysutils/attr/files/patch-darwin.diff'
:info:patch Exit code: 1
:error:patch Failed to patch attr: command execution failed
:debug:patch Error code: CHILDSTATUS 3185 1`

**Comment by eirnym** [comment]
@21stcaveman It's worth a while to create new issue for the patch.
