### ISSUE TITLE
phonon-qt5: destroot fails

### ISSUE THREAD

**Issue by 21stcaveman** [RJVB/macstrop#99]
Hello again!

phonon-qt5 fails with below:
:info:destroot CMake Error at settings/cmake_install.cmake:49 (file):
:info:destroot   file called with network path DESTINATION.  This does not make sense when
:info:destroot   using DESTDIR.  Specify local absolute path or remove DESTDIR environment
:info:destroot   variable.
:info:destroot   DESTINATION= 
:info:destroot   //Applications/MacPorts/KF5

**Comment by RJVB** [comment]
>:info:destroot   file called with *network* path DESTINATION.  This does not make sense when
...
>:info:destroot   DESTINATION= 
>:info:destroot   //Applications/MacPorts/KF5

This must be a (new) CMake feature that (almost) makes sense, but AFAIK only on MS Windows. I'll look into this when I get back to my Mac but in the meantime (if there is one...) could you tell me what CMake version you're using? I know I haven't upgraded the version in my tree for a while so it wouldn't hurt to do that first if you have a newer version installed from the main tree.

Clearly I didn't run into this when I last built my phonon-qt5 install with the CMake version I had back then!

**Comment by 21stcaveman** [comment]
I didn't run into this a few months ago when I was doing upgrade either, so must be something recent. I'm running cmake 3.24.4

latest commit doesn't seem to take care of it unfortunately.

**Comment by RJVB** [comment]
>I didn't run into this a few months ago when I was doing upgrade either, so must be something recent. I'm running cmake 3.24.4

There was an issue with port:phonon-qt5 where it didn't specify a bundle install location. My latest commit fixed that. There's a hidden file in `port work phonon-qt5`, called .macports.phonon-qt5.configure.cmd . I'd need to see its contents to understand this issue a bit better. The install location does not have a double slash on my end.

**Comment by RJVB** [comment]
>latest commit doesn't seem to take care of it unfortunately.

The KF5 PortGroup has:

```
        if {![info exists kf5.applications_dir]} {
            set kf5.applications_dir \
                            ${applications_dir}/KF5
        }
        configure.args-append \
                            -DBUNDLE_INSTALL_DIR=${kf5.applications_dir} \
```

I'm assuming you do not set kf5.applications_dir yourself, so the only way I see that a double slash could end up (`//Applications/Macports/KF5`) is if ${applications_dir} has one... and as far as I can see MacPorts won't do that itself. However, you can override the variable in $prefix/etc/macports/macports.conf, maybe check if something glitched in there?

I'd really need to see that ????.configure.cmd file otherwise!

**Comment by 21stcaveman** [comment]
interesting.. so I edited the build/settings/cmake_install.cmake file manually and removed the extra /, and all goes well. Installed the port manually.
I don't have a .macports.phonon-qt5.configure.cmd file in my work directory, I only have .macports.phonon-qt5.state

gonna close this issue, most probably something on my machine adding that extra / then based on what you explained.

**Comment by RJVB** [comment]
Fine, and good news.

You did a `port clean phonon-qt5` after pulling the latest version, right? ;)

**Comment by 21stcaveman** [comment]
sure did
